blog_website/blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='index'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    path('gallery/', views.PostListView.as_view(), name='post_list'),
    path('gallery/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('picture/<path:url>/', views.view_image, name='picture'),
    ]

blog_website/blog_website/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
# from django.views.static import serve
from django.contrib.staticfiles.views import serve

from blog.views import RangeFileView

handler404 = 'blog.views.page_not_found'
handler500 = 'blog.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('blog.urls', namespace='blog')),
    re_path(r'^media/(?P<path>.*)$', RangeFileView.as_view(), name='media'),
]


urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)
urlpatterns += i18n_patterns(
    path('', include('blog.urls')),
)


# urlpatterns += [
#     re_path(r'^media/(?P<path>.*)$',
#             serve, {'document_root': settings.MEDIA_ROOT, }),
# ]
# urlpatterns += [
#     re_path(r'^static/(?P<path>.*)$',
#             serve, {'document_root': settings.STATIC_ROOT, }),
# ]

blog_website/blog/models.py
import os
from django.db import models
from django.contrib.auth import get_user_model
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts", default="", verbose_name='Автор')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    published_date = models.DateField(verbose_name='Дата публикации')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')
    video_link = models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class CustomFileSystemStorage(models.FileField):
    def delete(self, name):
        try:
            super().delete(name)
        except FileNotFoundError:
            pass  # Ignore if the file doesn't exist


class PostImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = CustomFileSystemStorage(_("Image"), upload_to='post_images/')

    def __str__(self):
        return f"Image for post: {self.post}"


@receiver(models.signals.post_delete, sender=PostImage)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `PostImage` object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=PostImage)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `PostImage` object is updated
    with a new file.
    """
    if not instance.pk:
        return False

    try:
        old_image = PostImage.objects.get(pk=instance.pk).image
    except PostImage.DoesNotExist:
        return False

    new_image = instance.image
    if not old_image == new_image:
        if os.path.isfile(old_image.path):
            os.remove(old_image.path)


class PostVideo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='videos')
    video = CustomFileSystemStorage(_("Video"), upload_to='post_videos/')

    def __str__(self):
        return f"Video for post: {self.post}"


@receiver(models.signals.post_delete, sender=PostVideo)
def auto_delete_file_on_delete_video(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `PostVideo` object is deleted.
    """
    if instance.video:
        if os.path.isfile(instance.video.path):
            os.remove(instance.video.path)


@receiver(models.signals.pre_save, sender=PostVideo)
def auto_delete_file_on_change_video(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `PostVideo` object is updated
    with a new file.
    """
    if not instance.pk:
        return False

    try:
        old_video = PostVideo.objects.get(pk=instance.pk).video
    except PostVideo.DoesNotExist:
        return False

    new_video = instance.video
    if not old_video == new_video:
        if os.path.isfile(old_video.path):
            os.remove(old_video.path)

blog_website/blog/forms.py
from django import forms

from blog_website.blog.models import Post, PostImage, PostVideo


class PostForm(forms.ModelForm):
    """post creating form"""
    images = forms.ModelMultipleChoiceField(
        queryset=PostImage.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    videos = forms.ModelMultipleChoiceField(
        queryset=PostVideo.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    title_ru = forms.CharField(label='Заголовок', max_length=100)
    text_ru = forms.CharField(label='Текст', widget=forms.Textarea)
    title_en = forms.CharField(label='Заголовок на английском', max_length=100)
    text_en = forms.CharField(label='Текст на английском', widget=forms.Textarea)

    class Meta:
        model = Post
        fields = ('title_ru', 'text_ru', 'title_en', 'text_en', 'author', 'published_date', 'is_published', 'images', 'videos')
        labels = {
            # "title": "Заголовок",
            # "text": "Текст",
            "author": "Автор",
            "published_date": "Дата публикации",
            "is_published": "Опубликовано",
            "images": "Фото",
            "videos": "Видео"
        }
        widgets = {
            # 'title': forms.TextInput(attrs={'class': 'form-control'}),
            # 'text': forms.Textarea(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'published_date': forms.DateInput(attrs={'class': 'form-control'}),
            'is_published': forms.CheckboxInput(attrs={'class': 'form-control'}),
            'images': forms.FileInput(attrs={'class': 'form-control'}),
            'videos': forms.FileInput(attrs={'class': 'form-control'}),
        }

blog_website/blog/views.py
from django.http import Http404, FileResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.utils import timezone

from django.views.generic import TemplateView, ListView, DetailView

from blog.models import Post

from django.http import HttpResponse, HttpResponseNotFound
from django.utils.http import http_date
from django.views import View
from django.conf import settings
import os
from urllib.parse import unquote


class MainPageView(TemplateView):
    template_name = 'blog/home_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_name'] = self.request.resolver_match.view_name
        return context


class AboutPageView(TemplateView):
    template_name = 'blog/about_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_name'] = self.request.resolver_match.view_name
        return context


class ContactPageView(TemplateView):
    template_name = 'blog/contacts_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_name'] = self.request.resolver_match.view_name
        return context


class PostListView(ListView):
    template_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(
            is_published=True,
            published_date__lte=timezone.now(),
        ).order_by('-published_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_name'] = self.request.resolver_match.view_name
        return context


class PostDetailView(DetailView):
    template_name = 'blog/post_detail.html'
    model = Post

    def dispatch(self, request, *args, **kwargs):
        post = get_object_or_404(
            Post.objects.select_related('author'),
            pk=self.kwargs['pk'],
            is_published=True,
            published_date__lte=timezone.now(),
        )
        self.object = post
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_name'] = self.request.resolver_match.view_name
        context['images'] = self.object.images.all().prefetch_related('image')
        context['videos'] = self.object.videos.all().prefetch_related('video')
        return context


def page_not_found(request, exception):
    return render(request, 'custom_errors/404.html', status=404)


def server_error(request):
    return render(request, 'custom_errors/500.html', status=500)


class RangeFileView(View):
    def get(self, request, path):
        file_path = os.path.join(settings.MEDIA_ROOT, path)

        if not os.path.exists(file_path):
            return HttpResponseNotFound("File not found")

        response = HttpResponse()
        response['Accept-Ranges'] = 'bytes'

        try:
            with open(file_path, 'rb') as file:
                response.write(file.read())
        except FileNotFoundError:
            return HttpResponseNotFound("File not found")

        return response


def view_image(request, url):
    cleaned_url = os.path.normpath(url.lstrip('/').replace('media/', ''))
    image_path = os.path.join(settings.MEDIA_ROOT, cleaned_url)

    if os.path.exists(image_path):
        return FileResponse(open(image_path, 'rb'), content_type='image/png')
    else:
        print(f'The file {image_path} does not exist.')
        raise Http404('Image not found')

blog_website/templates/blog/about_page.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="about-page">
    <h1>{% trans "Остров Нега" %}</h1>
    <p>
        {% trans "Остров Нега был открыт 23 июля 2022 года группой художников." %}
    </p>
    <p>
        {% trans "Остров Нега является составной частью Капустинского центра современного искусства, экспериментальным, художественным пространством и заповедником под открытым небом. Здесь проводятся выставки, театральные представления, съёмки фильмов, концерты и другие мероприятия культуры и искусства." %}
    </p>
    <p>
        {% trans "Попадая на остров Нега во время мероприятия вы можете присоединиться к зрителям или участникам, по возможности, не нарушая правил приличия и уважения. Если вы посетите остров Нега в момент отсутствия мероприятия просим относиться к природе острова с уважением. Если вы будете пользоваться предметами, оставленными художниками, то вы их не можете забирать с собой и должны оставить в чистом виде и в рабочем состоянии. Относитесь к бытовым и художественным объектам острова с почтением. Не разжигайте костёр без особой необходимости. Если же это случилось не забудьте затушить его водой." %}
    </p>
    <p>
        {% trans "Проследите чтобы после вашего посещения на острове не оставался мусор. Мы верим в то, что большинство людей на Планете разделяют наши взгляды и готовы к разумному и гармоничному существованию." %}
    </p>
</div>
{% endblock %}

blog_website/templates/blog/contacts_page.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="contact-page">
    <h1>{% trans "Контакты" %}</h1>
    <p>
        {% trans "Если у вас есть вопросы, предложения или просто хочется связаться с нами, вы можете использовать следующие контактные данные:" %}
    </p>
    <p>
        <strong>{% trans "Телеграм: " %}</strong><a href="https://t.me/Sergei_Katran" target="_blank">{% trans "https://t.me/Sergei_Katran" %}</a>
    </p>

    <div class="mt-4">
        <img src="{% static 'blog/cabbage_2.gif' %}" alt="Купусточка" class="img-fluid" width="300">
    </div>

</div>
{% endblock %}

blog_website/templates/blog/home_page.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load i18n %}


{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 mb-4">
            <div class="container p-3 bg-purple text-center">
                <h2 class="text-white">{% trans "Капустинский центр современного искусства" %}</h2>
            </div>

            <div class="container mt-4">
                <img src="{% static 'blog/cabbage_1.gif' %}" alt="Cabbage" class="img-fluid" width="600">
            </div>

        </div>
        <div class="col-md-6">
            <p class="text-muted">{% trans "Капустинский центр современного искусства - самоорганизация художников, разделяющих любовь к современному искусству."%}</p>
            <p class="text-muted">{% trans "Мы верим в идею совместной и органичной деятельности основанной на равноправии и общем деле создания культурной среды."%}</p>
            <p class="text-muted">{% trans "Наше сообщество ценит независимость и непринужденное взаимодействие. Мы уделяем внимание разнообразию идей и творческому диалогу."%}</p>
            <p class="text-muted">{% trans "Нам близки идеи сохранения окружающей среды и существования человека в мире гармонии и любви."%}</p>
            <p class="text-muted">{% trans "Если вас привлекает идея творчества и хотите поделиться своим видением, не стесняйтесь связаться с нами."%}</p>
        </div>
    </div>
</div>


<style>
    /* Background styles for the purple container */
    .bg-purple {
        background-color: #0E86D4; /* Use your preferred shade of purple */
        border-radius: 10px;
    }

    /* Text styles for the headers */
    .text-white {
        color: #fff; /* White text color */
    }

    /* Spacing for the main content */
    .container {
        padding: 20px; /* Add some padding to the container */
    }

    /* Additional styles for the text */
    .text-muted {
        font-size: 16px;
        line-height: 1.5;
        margin-bottom: 15px;
    }
</style>
{% endblock %}

blog_website/templates/blog/post_detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">


<div class="container mt-4">
        <h1>{{ object.title }}</h1>
    </div>
    <div class="container mt-4">
        <div class="card">
            <div class="card-body">
                <p class="card-text">{{ object.text }}</p>
                <p class="card-text"><small class="text-muted">Published on {{ object.published_date }}</small></p>


                {% if object.videos.all %}
                    <div class="video-container">
                        {% for video_instance in object.videos.all %}
                            <div style="margin-bottom: 20px;">
                                <video controls class="plyr" data-plyr-provider="html5" data-plyr-embed-id="{{ video_instance.video.url }}">
                                    <source src="{{ video_instance.video.url }}" type="video/mp4">
                                    Your browser does not support the video tag.
                                </video>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}

                {% if post.video_link %}
                    <p>YouTube: <a href="{{ post.video_link }}">{{ post.video_link }}</a></p>
                {% endif %}

                {% if object.images.all %}
                    <div class="image-container mt-4">
                        <div class="row">
                            {% for image in object.images.all %}
                                <div class="col-md-4 mb-4">
                                    <a href="{% url 'blog:picture' url=image.image.url %}" target="_blank">
                                    <img src="{{ image.image.url }}" alt="Image not loaded" class="img-fluid" />
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>

<script>
        document.addEventListener("DOMContentLoaded", function () {
            const videos = document.querySelectorAll(".plyr");
            videos.forEach(function (video) {
                new Plyr(video);
            });
        });

</script>
{% endblock %}

blog_website/templates/blog/post_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load i18n %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

<div class="container mt-4">
    <h1>{% trans "Галерея" %}</h1>
</div>
<div class="container mt-4">
    <div class="row">
        {% for post in post_list %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text mb-12">{{ post.text|truncatechars:200 }}</p>
                    </div>
                    <br>

                    <div class="mb-6"><footer class="blockquote-footer">{{ post.published_date }}</footer></div>
                    <div class="card-footer">
                        <a href="{% url 'blog:post_detail' post.pk %}" class="btn custom-button">{% trans "Подробно" %}</a>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}