blog_website/blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='index'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    path('gallery/', views.PostListView.as_view(), name='post_list'),
    path('gallery/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('picture/<path:url>/', views.view_image, name='picture'),
    ]

blog_website/blog_website/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
# from django.views.static import serve
from django.contrib.staticfiles.views import serve

from blog.views import RangeFileView

handler404 = 'blog.views.page_not_found'
handler500 = 'blog.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('blog.urls', namespace='blog')),
    re_path(r'^media/(?P<path>.*)$', RangeFileView.as_view(), name='media'),
]


urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)
urlpatterns += i18n_patterns(
    path('', include('blog.urls')),
)


# urlpatterns += [
#     re_path(r'^media/(?P<path>.*)$',
#             serve, {'document_root': settings.MEDIA_ROOT, }),
# ]
# urlpatterns += [
#     re_path(r'^static/(?P<path>.*)$',
#             serve, {'document_root': settings.STATIC_ROOT, }),
# ]

blog_website/templates/includes/footer.html
{% load static %}
{% load i18n %}

{% block footer %}
<footer class="bg-light p-3 text-center">
    &copy; {% trans "2025 Капустинский центр современного искусства" %}
</footer>
{% endblock %}

blog_website/templates/includes/header.html
{% load static %}
{% load i18n %}

{% block navbar %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'blog:index' %}">
        <div class="container mt-4">
                <img src="{% static 'blog/cabbage_1_img.png' %}" alt="КЦСИ" class="img-fluid" width="65">
            <div class="col-8">
            <h1>КЦСИ</h1>
        </div>
        </div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">

                <a class="nav-link {% if view_name == 'blog:index' %} active {% endif %}"
                   href="{% url 'blog:index' %}">{% trans "Главная" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name == 'blog:post_list' %} active {% endif %}"
                   href="{% url 'blog:post_list' %}">{% trans "Галерея" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name == 'blog:about' %} active {% endif %}"
                   href="{% url 'blog:about' %}">{% trans "Остров Нега" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view_name == 'blog:contact' %} active {% endif %}"
                   href="{% url 'blog:contact' %}">{% trans "Контакты" %}</a>
            </li>
            </ul>
            <ul class="navbar-nav ml-auto">
            <li>
                <form action="{%url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />
                    <select name="language">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                    selected{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="Go" />
                </form>
            </li>
        </ul>

    </div>
</nav>

<!-- Bootstrap Scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


{% endblock %}